/**
 * Generates the JSON UI reference (docs/json-ui-ref.md) from the '_doc'
 * properties in the JSON UI files listed in packs/RP/ui/_ui_defs.json.
 *
 * '_doc' is not valid JSON UI, so it is stripped at build time by the
 * 'strip_ui_docs' filter (see scripts/filters/strip_ui_docs.ts).
 */

import * as fs from "fs";
import * as prettier from "prettier";

const rpDir = "packs/RP";
const uiDefsPath = `${rpDir}/ui/_ui_defs.json`;
const outPath = "docs/json-ui-ref.md";
const srcUrl =
  "https://github.com/Fluffyalien1422/bedrock-energistics-core/blob/main";

/**
 * A '_doc' property. Valid on a namespace (the top level of a JSON UI file) and
 * on the top level of each element in that namespace.
 */
interface Doc {
  /** A short description of the namespace or element. */
  summary?: string;
  /** Additional details that don't belong in the summary. */
  remarks?: string;
  /** Descriptions of the element's props (variables), keyed by prop name. */
  props?: Record<string, string>;
  /** `true`, or a string explaining what to use instead. */
  deprecated?: boolean | string;
}

interface UiFile {
  namespace?: string;
  _doc?: Doc;
  /** Everything else is an element. */
  [name: string]: unknown;
}

const header = `---
title: JSON UI Reference
---

<!-- Generated by scripts/gen_json_ui_ref.ts. Run \`npm run docs\` to regenerate. Do not edit by hand. -->

# JSON UI Reference

Reference for the JSON UI elements provided by Bedrock Energistics Core. These elements are available to any add-on that depends on Bedrock Energistics Core, you do not need to copy them into your own pack.

See the [Machine UI](guides/machine-ui.md) guide for an overview of how machine UIs work.`;

/**
 * Renders the body of a namespace or element section as markdown, excluding the
 * heading. 'details' are the labelled lines shown before the summary, such as
 * the fully qualified name. Namespaces and elements are listed even if they
 * have no '_doc', in which case the body is just the details.
 */
function renderBody(doc: Doc | undefined, details: string[]): string[] {
  const parts: string[] = [];

  if (doc?.deprecated !== undefined && doc.deprecated !== false) {
    parts.push(
      typeof doc.deprecated === "string"
        ? `**Deprecated.** ${doc.deprecated}`
        : "**Deprecated.**",
    );
  }

  parts.push(...details);

  if (doc?.summary) {
    parts.push(doc.summary);
  }

  if (doc?.remarks) {
    parts.push(doc.remarks);
  }

  if (doc?.props !== undefined) {
    const props = Object.entries(doc.props).map(
      ([name, description]) => `- \`${name}\` - ${description}`,
    );

    parts.push(`**Props:**\n\n${props.join("\n")}`);
  }

  return parts;
}

const uiDefs = JSON.parse(fs.readFileSync(uiDefsPath, "utf8")) as {
  ui_defs: string[];
};

const parts = [header];

for (const uiDef of uiDefs.ui_defs) {
  const file = JSON.parse(
    fs.readFileSync(`${rpDir}/${uiDef}`, "utf8"),
  ) as UiFile;

  const namespace = file.namespace;

  if (namespace === undefined) {
    console.warn(`Skipping '${uiDef}', it has no namespace.`);
    continue;
  }

  const srcPath = `${rpDir}/${uiDef}`;

  parts.push(
    `## ${namespace}`,
    ...renderBody(file._doc, [
      `**Source:** [${srcPath}](${srcUrl}/${srcPath})`,
    ]),
  );

  for (const [key, element] of Object.entries(file)) {
    if (key === "namespace" || key === "_doc") continue;
    if (typeof element !== "object" || element === null) continue;

    // an element key may name the element it extends after an '@',
    // e.g. 'foo@namespace.bar' extends 'namespace.bar'
    const atIndex = key.indexOf("@");
    const name = atIndex === -1 ? key : key.slice(0, atIndex);
    const extendsRef = atIndex === -1 ? undefined : key.slice(atIndex + 1);

    const details = [`**Fully qualified name:** \`${namespace}.${name}\``];

    if (extendsRef !== undefined) {
      details.push(`**Extends:** \`${extendsRef}\``);
    }

    parts.push(
      `### ${name}`,
      ...renderBody((element as { _doc?: Doc })._doc, details),
    );
  }
}

const prettierConfig = await prettier.resolveConfig(outPath);

fs.writeFileSync(
  outPath,
  await prettier.format(`${parts.join("\n\n")}\n`, {
    ...prettierConfig,
    filepath: outPath,
  }),
);

console.log(`Wrote '${outPath}'.`);
